version: "3"
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: "git.tu-berlin.de:5000/heimdall/iosl-st-23/frontend"
    container_name: frontend
    command: npm start
    volumes:
      - ./frontend/:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "3000:3000"
    # backend:
    #   build: ./backend
    #   ports:
    #     - "5000:5000"
